### ISSUE TITLE
chews through CPU b/c no framerate limit

### ISSUE THREAD

**Issue by jaredly** [bsansouci/reasongl-native#2]
on web you use `requestAnimationFrame` which calls `tick` at most 60fps, but there's not equivalent here. Should have some `sleep` or something to make `tick` be called at most 60fps

**Comment by bsansouci** [comment]
After some tinkering I added a non-cross platform solution https://github.com/bsansouci/reasongl-native/commit/c2599c3f00878e3b5af551a5a30274dbb624bbda. It'll sleep only if it has 2ms or more to sleep, otherwise it busy loops. The reason is that it seemed like the whole sleep thing was precise to +-1ms... The render loop should still be called 60 times a second. If a frame takes longer than 1/60th of a second, we'll call the user's render method however many times it takes to catch up and then won't sleep (because we're late).

So if you're taking the whole 16ms of the frame, no sleep will occur.
